server:
  port: 8083

spring:
  application:
    name: nacos-payment-order
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.112:8848

#\u6D88\u8D39\u8005\u8981\u53BB\u8BBF\u95EE\u7684\u5FAE\u670D\u52A1\u540D\u79F0\uFF08\u6210\u529F\u6CE8\u518C\u8FDBnacos\u7684\u5FAE\u670D\u52A1\u63D0\u4F9B\u8005\uFF09
service-url:
  nacos-user-service: http://nacos-payment-provider