server:
  port: 3344

spring:
  application:
    name: cloud-config-center

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #git\u914D\u7F6E
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GitWucxHub/springcloud-config.git
          search-paths:
            - springcloud-config
          username: GitWucxHub
          password: Wucx2020skywzx
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:

    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka

  instance:
    instance-id: cloud-config-center3344
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
