server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true           #\u5F00\u542F\u4ECE\u6CE8\u518C\u4E2D\u5FC3\u52A8\u6001\u521B\u5EFA\u8DEF\u7531\u7684\u529F\u80FD\uFF0C\u5229\u7528\u5FAE\u670D\u52A1\u8FDB\u884C\u8DEF\u7531
      routes:
        - id: payment_routh             #\u8DEF\u7531\u7684id\uFF0C\u6CA1\u6709\u56FA\u5B9A\u89C4\u5219\u4F46\u8981\u6C42\u552F\u4E00\uFF0C\u5EFA\u8BAE\u914D\u5408\u670D\u52A1\u540D
          #uri: http://localhost:8001    # \u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
          uri: lb://CLOUD-PAYMENT-SERVICE #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
          predicates:
            - Path=/payment/get/**       #\u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
          predicates:
            - Path=/payment/lb/**
            - After=2021-02-14T21:55:14.863+08:00[Asia/Shanghai]
            # - Cookie=chocolate,wucx
            #- Header=X-Request-Id, \d+   #\u8BF7\u6C42\u5934\u8981\u6709X-Request-Id\u5C5E\u6027\u5E76\u4E14\u4E3A\u6574\u6570\u7684\u6B63\u5219\u8868\u8FBE\u5F0F


eureka:
  client:
    #
    register-with-eureka: true
    #
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
    hostname: cloud-gateway-service