
server:
  port: 8007
spring:
  application:
    name: cloud-payment-provider-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.112:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  freemarker:
    content-type: text/html
    suffix: .ftlh
    template-loader-path: classpath:/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.alphago.springcloud.entities

eureka:
  client:
    #
    register-with-eureka: true
    #
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    instance-id: payment8007
    prefer-ip-address: true