

server:
  port: 7000

eureka:
  instance:
    #eureka\u670D\u52A1\u7AEF\u6CE8\u518C\u7684\u5B9E\u4F8B\u540D\u79F0
    hostname: localhost
  client:
    #false\u8868\u793A\u4E0D\u5411\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u81EA\u5DF1
    register-with-eureka: false
    #flase\u8868\u793A\u81EA\u5DF1\u7AEF\u5C31\u662F\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u804C\u8D23\u5C31\u662F\u7EF4\u62A4\u670D\u52A1\u5B9E\u4F8B\uFF0C\u5E76\u4E0D\u9700\u8981\u68C0\u7D22\u670D\u52A1
    fetch-registry: false
    service-url:
      #\u8BBE\u7F6E\u4E0Eeureka Server\u4EA4\u4E92\u7684\u5730\u5740\u67E5\u8BE2\u670D\u52A1\u548C\u6CE8\u518C\u670D\u52A1\u90FD\u9700\u8981\u8FD9\u4E2A\u5730\u5740
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #\u81EA\u6211\u4FDD\u62A4\u6A21\u5F0F\uFF0C\u9ED8\u8BA4\u4E3Atrue\u4E3A\u5F00\u542F\u4FDD\u62A4\uFF0C\u6B64\u5904\u8BBE\u7F6E\u4E3Afalse
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
