
server:
  port: 8082

spring:
  application:
    name: cloud-consumer-order


  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    consul:
      host: 192.168.0.112
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true