
#8004\u8868\u793A\u6CE8\u518C\u5230consul\u670D\u52A1\u5668\u7684\u652F\u4ED8\u670D\u52A1\u63D0\u4F9B\u7AEF\u53E3\u53F7
server:
  port: 8082

#\u670D\u52A1\u522B\u540D------------\u6CE8\u518Cconsul\u5230\u6CE8\u518C\u4E2D\u5FC3\u540D\u79F0
spring:
  application:
    name: cloud-consumer-order


  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #consul\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  cloud:
    consul:
      host: 192.168.0.112
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true